// AUTH
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const GET_USER_INFO = 'GET_USER_INFO';
export const CREATE_USER = 'CREATE_USER';

// EVENT
export const FETCH_ALL_EVENT = 'FETCH_ALL_EVENT';
export const FETCH_MY_EVENT = 'FETCH_MY_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT'

//CUSTOMER
export const UPDATE_CUSTOMERS_INFO = 'UPDATE_CUSTOMERS_INFO';
export const LIKE_EVENT = 'LIKE_EVENT';
export const UPDATE_CUSTOMERS_EMAIL = 'UPDATE_CUSTOMERS_EMAIL';
export const UPDATE_CUSTOMERS_NAME_EMAIL = 'UPDATE_CUSTOMERS_NAME_EMAIL';

//COUNTRY
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_DETAILS = 'GET_COUNTRY_DETAILS';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'